apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex202-todo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ex202-todo-backend
  template:
    metadata:
      labels:
        app: ex202-todo-backend
    spec:
      containers:
        - name: ex202-todo-backend
          image: dilansachi/devopswk8s-ex202-todo-backend:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3003"
