apiVersion: v1
kind: Service
metadata:
  name: ex202-todo-backend-svc
spec:
  type: ClusterIP
  selector:
    app: ex202-todo-backend
  ports:
    - name: todo-backend
      port: 2346
      protocol: TCP
      targetPort: 3003
