apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex202-todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ex202-todo-app
  template:
    metadata:
      labels:
        app: ex202-todo-app
    spec:
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: ex202-vol-claim
      containers:
        - name: ex202-todo-app
          image: dilansachi/devopswk8s-ex202-todo-app:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3002"
          volumeMounts:
            - name: shared-volume
              mountPath: /usr/src/app/files
