apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/cpu-usage-analysis-template.yaml
  - manifests/statefulset.yaml
  - manifests/configmap.yaml
  - manifests/persistent-vol-claim.yaml
  - manifests/ping-pong-app-deployment-rollout.yaml
  - manifests/log-app-deployment-rollout.yaml
  - manifests/log-app-service.yaml
  - manifests/ping-pong-app-service.yaml
  - manifests/gateway.yaml
  - manifests/route.yaml
images:
  - name: PROJECT/LOG_READER_IMAGE
    newName: dilansachi/devopswk8s-ex404-log-reader:1.0.0
  - name: PROJECT/LOG_WRITER_IMAGE
    newName: dilansachi/devopswk8s-ex404-log-writer:1.0.0
  - name: PROJECT/PING_PONG_APP_IMAGE
    newName: dilansachi/devopswk8s-ex404-ping-pong-application:1.0.0
