apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ex206-vol-claim
  namespace: project
spec:
  storageClassName: ex206-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
