apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ex311-dep-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ex311
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 50
