apiVersion: stable.dwk.stable.dwk/v1
kind: DummySite
metadata:
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/managed-by: kustomize
  name: dummysite-sample
spec:
  website_url: "https://example.com"
