apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: ex306-route
spec:
  parentRefs:
    - name: ex306-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: ex306-svc
          port: 2345
    - matches:
        - path:
            type: PathPrefix
            value: /image
      backendRefs:
        - name: ex306-svc
          port: 2345
    - matches:
        - path:
            type: PathPrefix
            value: /gettodos
      backendRefs:
        - name: ex306-svc
          port: 2346
    - matches:
        - path:
            type: PathPrefix
            value: /addtodo
      backendRefs:
        - name: ex306-svc
          port: 2346
