apiVersion: v1
kind: Service
metadata:
  name: ex306-svc
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: ex306
  ports:
    - name: todo-app
      port: 2345
      protocol: TCP
      targetPort: 3002
    - name: todo-backend
      port: 2346
      protocol: TCP
      targetPort: 3003
