apiVersion: v1
kind: Service
metadata:
  name: ex503-greeter-app-svc
  namespace: exercises
spec:
  selector:
    app: ex503-greeter-app
  ports:
    - name: greeter-app
      port: 2347
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ex503-greeter-app-svc-v1
  namespace: exercises
spec:
  type: ClusterIP
  selector:
    app: ex503-greeter-app
    version: v1
  ports:
    - name: greeter-app
      port: 2347
      protocol: TCP
      targetPort: 3004
---
apiVersion: v1
kind: Service
metadata:
  name: ex503-greeter-app-svc-v2
  namespace: exercises
spec:
  type: ClusterIP
  selector:
    app: ex503-greeter-app
    version: v2
  ports:
    - name: greeter-app
      port: 2347
      protocol: TCP
      targetPort: 3004
