apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex503-greeter-app
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ex503-greeter-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ex503-greeter-app
    spec:
      containers:
        - name: ex503-greeter-application
          image: PROJECT/GREETER_APP_IMAGE
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3004"
            - name: GREET_VERSION
              value: "01"
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            httpGet:
              path: /healthz
              port: 3004
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            httpGet:
              path: /healthz
              port: 3004
