apiVersion: v1
kind: Service
metadata:
  name: ex503-greeter-app-svc
  namespace: exercises
spec:
  type: ClusterIP
  selector:
    app: ex503-greeter-app
  ports:
    - name: greeter-app
      port: 2347
      protocol: TCP
      targetPort: 3004
