apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex312
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ex312
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ex312
    spec:
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: ex312-vol-claim
      containers:
        - name: ex312-todo-app
          image: PROJECT/TODO_APP_IMAGE
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3002"
            - name: IMAGE_FILE_PATH
              valueFrom:
                configMapKeyRef:
                  name: ex312-config-map
                  key: image_file_path
            - name: IMAGE_RESOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: ex312-config-map
                  key: image_resource_url
          volumeMounts:
            - name: shared-volume
              mountPath: /usr/src/app/files
          resources:
            limits:
              cpu: "200m"
              memory: "100Mi"
            requests:
              cpu: "50m"
              memory: "25Mi"
        - name: ex312-todo-backend
          image: PROJECT/TODO_BACKEND_IMAGE
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3003"
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: ex312-config-map
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: ex312-config-map
                  key: DB_PASSWORD
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: ex312-config-map
                  key: DB_URL
          resources:
            limits:
              cpu: "200m"
              memory: "100Mi"
            requests:
              cpu: "50m"
              memory: "25Mi"
