apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ex312-dep-hpa
  namespace: project
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ex312
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 50
