apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ex210-vol-claim
  namespace: project
spec:
  storageClassName: ex210-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
