apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex210-todo-app
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ex210-todo-app
  template:
    metadata:
      labels:
        app: ex210-todo-app
    spec:
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: ex210-vol-claim
      containers:
        - name: ex210-todo-app
          image: dilansachi/devopswk8s-ex210-todo-app:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3002"
            - name: IMAGE_FILE_PATH
              valueFrom:
                configMapKeyRef:
                  name: ex210-config-map
                  key: image_file_path
            - name: IMAGE_RESOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: ex210-config-map
                  key: image_resource_url
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: ex210-config-map
                  key: backend_url
          volumeMounts:
            - name: shared-volume
              mountPath: /usr/src/app/files
