apiVersion: v1
kind: Service
metadata:
  name: ex112-svc
spec:
  type: ClusterIP
  selector:
    app: ex112
  ports:
    - name: image-application
      port: 2345
      protocol: TCP
      targetPort: 3002
