apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex103-log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ex103
  template:
    metadata:
      labels:
        app: ex103
    spec:
      containers:
        - name: ex103
          image: dilansachi/devopswk8s-ex103:1.0.0
          imagePullPolicy: IfNotPresent
