apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/cpu-usage-analysis-template.yaml
- manifests/statefulset.yaml
- manifests/configmap.yaml
- manifests/persistent-vol-claim.yaml
- manifests/ping-pong-app-deployment.yaml
- manifests/log-app-deployment.yaml
- manifests/log-app-service.yaml
- manifests/ping-pong-app-service.yaml
- manifests/gateway.yaml
- manifests/route.yaml
images:
- name: PROJECT/LOG_READER_IMAGE
  newName: dilansachi/devopswk8s-ex407-log-reader
  newTag: main-7f14b7f5b082993fee0bfdb1ac038ec1fdf92d9a
- name: PROJECT/LOG_WRITER_IMAGE
  newName: dilansachi/devopswk8s-ex407-log-writer
  newTag: main-7f14b7f5b082993fee0bfdb1ac038ec1fdf92d9a
- name: PROJECT/PING_PONG_APP_IMAGE
  newName: dilansachi/devopswk8s-ex407-ping-pong-application
  newTag: main-7f14b7f5b082993fee0bfdb1ac038ec1fdf92d9a
namespace: exercises
