apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ex209-ingress
  namespace: project
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: ex209-svc
                port:
                  number: 2345
          - path: /image
            pathType: Exact
            backend:
              service:
                name: ex209-svc
                port:
                  number: 2345
          - path: /gettodos
            pathType: Exact
            backend:
              service:
                name: ex209-svc
                port:
                  number: 2346
          - path: /addtodo
            pathType: Exact
            backend:
              service:
                name: ex209-svc
                port:
                  number: 2346
