apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-usage-analysis
  namespace: exercises
spec:
  metrics:
  - name: cpu-usage-analysis
    initialDelay: 2m
    successCondition: result < 1
    provider:
      prometheus:
        address: http://kube-prometheus-stack-1767-prometheus.prometheus.svc.cluster.local:9090
        query: |
          scalar(sum by (namespace) (
            rate(container_cpu_usage_seconds_total{
            namespace="prometheus",
            container!=""
            }[5m])
          ))
