apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: ex404-route
  namespace: exercises
spec:
  parentRefs:
    - name: ex404-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /pingpong
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: ex404-ping-pong-app-svc
          port: 2346
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: ex404-log-app-svc
          port: 2345
