apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex409-todo-app
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ex409-todo-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ex409-todo-app
    spec:
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: ex409-vol-claim
      containers:
        - name: ex409-todo-app
          image: PROJECT/TODO_APP_IMAGE
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3002"
            - name: IMAGE_FILE_PATH
              valueFrom:
                configMapKeyRef:
                  name: ex409-config-map
                  key: image_file_path
            - name: IMAGE_RESOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: ex409-config-map
                  key: image_resource_url
          volumeMounts:
            - name: shared-volume
              mountPath: /usr/src/app/files
          resources:
            limits:
              cpu: "200m"
              memory: "100Mi"
            requests:
              cpu: "50m"
              memory: "25Mi"
