apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: ex303-route
spec:
  parentRefs:
    - name: ex303-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: ex303-svc
          port: 2345
    - matches:
        - path:
            type: PathPrefix
            value: /pingpong
      backendRefs:
        - name: ex303-svc
          port: 2346
