apiVersion: v1
kind: Service
metadata:
  name: ex302-log-app-svc
  namespace: exercises
spec:
  type: NodePort
  selector:
    app: ex302-log-app
  ports:
    - name: log-app
      port: 2345
      protocol: TCP
      targetPort: 3002
