apiVersion: v1
kind: Service
metadata:
  name: ex302-ping-pong-app-svc
  namespace: exercises
spec:
  type: NodePort
  selector:
    app: ex302-ping-pong-app
  ports:
    - name: ping-pong-app
      port: 2346
      protocol: TCP
      targetPort: 3003
