apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./../../base
- backup-postgres-job.yaml
patches:
- path: configmap.yaml
images:
- name: PROJECT/BROADCASTER_APP_IMAGE
  newName: dilansachi/devopswk8s-ex409-broadcaster-app
  newTag: 4.9-4a0bbc3ed062f36e4b4207194b15c7636db97b4a
- name: PROJECT/TODO_APP_IMAGE
  newName: dilansachi/devopswk8s-ex409-todo-app
  newTag: 4.9-4a0bbc3ed062f36e4b4207194b15c7636db97b4a
- name: PROJECT/TODO_BACKEND_IMAGE
  newName: dilansachi/devopswk8s-ex409-todo-backend
  newTag: 4.9-4a0bbc3ed062f36e4b4207194b15c7636db97b4a
namespace: project-prod
