apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex203-log-app
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ex203-log-app
  template:
    metadata:
      labels:
        app: ex203-log-app
    spec:
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: ex203-vol-claim
      containers:
        - name: ex203-log-reader
          image: dilansachi/devopswk8s-ex203-log-reader:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3002"
          volumeMounts:
            - name: shared-volume
              mountPath: /usr/src/app/files
        - name: ex203-log-writer
          image: dilansachi/devopswk8s-ex203-log-writer:1.0.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: shared-volume
              mountPath: /usr/src/app/files
