apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ex203-vol-claim
  namespace: exercises
spec:
  storageClassName: ex203-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
