apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex203-ping-pong-app
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ex203-ping-pong-app
  template:
    metadata:
      labels:
        app: ex203-ping-pong-app
    spec:
      containers:
        - name: ex203-ping-pong-application
          image: dilansachi/devopswk8s-ex203-ping-pong-application:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3003"
