apiVersion: v1
kind: Service
metadata:
  name: ex408-broadcaster-app-svc
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: ex408-broadcaster-app
  ports:
    - name: broadcaster-app
      port: 2345
      protocol: TCP
      targetPort: 3002
