apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex208-todo-backend
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ex208-todo-backend
  template:
    metadata:
      labels:
        app: ex208-todo-backend
    spec:
      containers:
        - name: ex208-todo-backend
          image: dilansachi/devopswk8s-ex208-todo-backend:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3003"
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: ex208-config-map
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: ex208-config-map
                  key: DB_PASSWORD
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: ex208-config-map
                  key: DB_URL
