apiVersion: v1
kind: Service
metadata:
  name: ex207-svc
  namespace: exercises
spec:
  type: ClusterIP
  selector:
    app: ex207
  ports:
    - name: log-reader
      port: 2345
      protocol: TCP
      targetPort: 3002
    - name: ping-pong-app
      port: 2346
      protocol: TCP
      targetPort: 3003
