apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex305-todo-backend
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ex305-todo-backend
  template:
    metadata:
      labels:
        app: ex305-todo-backend
    spec:
      containers:
        - name: ex305-todo-backend
          image: PROJECT/TODO_BACKEND_IMAGE
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3003"
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: ex305-config-map
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: ex305-config-map
                  key: DB_PASSWORD
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: ex305-config-map
                  key: DB_URL
