apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex305-todo-app
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ex305-todo-app
  template:
    metadata:
      labels:
        app: ex305-todo-app
    spec:
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: ex305-vol-claim
      containers:
        - name: ex305-todo-app
          image: PROJECT/TODO_APP_IMAGE
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3002"
            - name: IMAGE_FILE_PATH
              valueFrom:
                configMapKeyRef:
                  name: ex305-config-map
                  key: image_file_path
            - name: IMAGE_RESOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: ex305-config-map
                  key: image_resource_url
          volumeMounts:
            - name: shared-volume
              mountPath: /usr/src/app/files
