apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex201
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ex201
  template:
    metadata:
      labels:
        app: ex201
    spec:
      containers:
        - name: ex201-ping-pong-application
          image: dilansachi/devopswk8s-ex201-ping-pong-application:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3003"
        - name: ex201-log-reader
          image: dilansachi/devopswk8s-ex201-log-reader:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3002"
