apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./../../base
images:
- name: PROJECT/BROADCASTER_APP_IMAGE
  newName: dilansachi/devopswk8s-ex409-broadcaster-app
  newTag: main-1812a8caa9052779a6bbdb005f4f27c64031a178
- name: PROJECT/TODO_APP_IMAGE
  newName: dilansachi/devopswk8s-ex409-todo-app
  newTag: main-1812a8caa9052779a6bbdb005f4f27c64031a178
- name: PROJECT/TODO_BACKEND_IMAGE
  newName: dilansachi/devopswk8s-ex409-todo-backend
  newTag: main-1812a8caa9052779a6bbdb005f4f27c64031a178
namespace: project-staging
