apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./../../base
images:
- name: PROJECT/BROADCASTER_APP_IMAGE
  newName: dilansachi/devopswk8s-ex409-broadcaster-app
  newTag: main-5bf425e2872dc49e2d898cdd2cf30a9ef6911a3e
- name: PROJECT/TODO_APP_IMAGE
  newName: dilansachi/devopswk8s-ex409-todo-app
  newTag: main-5bf425e2872dc49e2d898cdd2cf30a9ef6911a3e
- name: PROJECT/TODO_BACKEND_IMAGE
  newName: dilansachi/devopswk8s-ex409-todo-backend
  newTag: main-5bf425e2872dc49e2d898cdd2cf30a9ef6911a3e
namespace: project-staging
