apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./../../base
images:
- name: PROJECT/BROADCASTER_APP_IMAGE
  newName: dilansachi/devopswk8s-ex409-broadcaster-app
  newTag: main-66cfb5d7c17bbb66dbda9f48eed22ceec777adfa
- name: PROJECT/TODO_APP_IMAGE
  newName: dilansachi/devopswk8s-ex409-todo-app
  newTag: main-66cfb5d7c17bbb66dbda9f48eed22ceec777adfa
- name: PROJECT/TODO_BACKEND_IMAGE
  newName: dilansachi/devopswk8s-ex409-todo-backend
  newTag: main-66cfb5d7c17bbb66dbda9f48eed22ceec777adfa
namespace: project-staging
