apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./../../base
images:
- name: PROJECT/BROADCASTER_APP_IMAGE
  newName: dilansachi/devopswk8s-ex409-broadcaster-app
  newTag: main-93575881392156b8d0e8c9f9ee00d81d21f0c588
- name: PROJECT/TODO_APP_IMAGE
  newName: dilansachi/devopswk8s-ex409-todo-app
  newTag: main-93575881392156b8d0e8c9f9ee00d81d21f0c588
- name: PROJECT/TODO_BACKEND_IMAGE
  newName: dilansachi/devopswk8s-ex409-todo-backend
  newTag: main-93575881392156b8d0e8c9f9ee00d81d21f0c588
namespace: project-staging
