apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: ex407-log-app
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ex407-log-app
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause:
            duration: 30s
        - setWeight: 50
        - pause:
            duration: 30s
        - analysis:
            templates:
              - templateName: cpu-usage-analysis
  template:
    metadata:
      labels:
        app: ex407-log-app
    spec:
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: ex407-vol-claim
        - name: config-vol
          configMap:
            name: ex407-config-map
            items:
              - key: "information.txt"
                path: "information.txt"
      containers:
        - name: ex407-log-reader
          image: PROJECT/LOG_READER_IMAGE
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3002"
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: ex407-config-map
                  key: MESSAGE
            - name: PING_PONG_APP_URL
              valueFrom:
                configMapKeyRef:
                  name: ex407-config-map
                  key: PING_PONG_APP_URL
          volumeMounts:
            - name: shared-volume
              mountPath: /usr/src/app/files
            - name: config-vol
              mountPath: "/config-vol"
              readOnly: true
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            httpGet:
              path: /healthz
              port: 3002
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            httpGet:
              path: /healthz
              port: 3002
        - name: ex407-log-writer
          image: PROJECT/LOG_WRITER_IMAGE
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: shared-volume
              mountPath: /usr/src/app/files
