apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: ex407-ping-pong-app
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ex407-ping-pong-app
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause:
            duration: 30s
        - setWeight: 50
        - pause:
            duration: 30s
        - analysis:
            templates:
              - templateName: cpu-usage-analysis
  template:
    metadata:
      labels:
        app: ex407-ping-pong-app
    spec:
      containers:
        - name: ex407-ping-pong-application
          image: PROJECT/PING_PONG_APP_IMAGE
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3003"
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: ex407-config-map
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: ex407-config-map
                  key: DB_PASSWORD
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: ex407-config-map
                  key: DB_URL
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            httpGet:
              path: /healthz
              port: 3003
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            httpGet:
              path: /healthz
              port: 3003
