apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex304
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ex304
  template:
    metadata:
      labels:
        app: ex304
    spec:
      containers:
        - name: ex304-ping-pong-application
          image: dilansachi/devopswk8s-ex304-ping-pong-application:1.0.0
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3003"
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: ex304-config-map
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: ex304-config-map
                  key: DB_PASSWORD
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: ex304-config-map
                  key: DB_URL
        - name: ex304-log-reader
          image: dilansachi/devopswk8s-ex304-log-reader:1.0.0
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3002"
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: ex304-config-map
                  key: MESSAGE
            - name: PING_PONG_APP_URL
              valueFrom:
                configMapKeyRef:
                  name: ex304-config-map
                  key: PING_PONG_APP_URL
          volumeMounts:
            - name: config-vol
              mountPath: "/config-vol"
              readOnly: true
      volumes:
        - name: config-vol
          configMap:
            name: ex304-config-map
            items:
              - key: "information.txt"
                path: "information.txt"
