apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex107-log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ex107
  template:
    metadata:
      labels:
        app: ex107
    spec:
      containers:
        - name: ex107
          image: dilansachi/devopswk8s-ex107:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3001"
