apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex109-ping-pong-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ex109-ping-pong-app
  template:
    metadata:
      labels:
        app: ex109-ping-pong-app
    spec:
      containers:
        - name: ex109-ping-pong-app
          image: dilansachi/devopswk8s-ex109:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3001"
