apiVersion: v1
kind: Service
metadata:
  name: ex109-ping-pong-app-svc
spec:
  type: ClusterIP
  selector:
    app: ex109-ping-pong-app
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3001
