apiVersion: batch/v1
kind: CronJob
metadata:
  name: ex310-backup-psql-job
  namespace: project
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ex310-backup-psql-runner
              image: postgres:alpine
              imagePullPolicy: IfNotPresent
              command:
                - /bin/bash
                - -c
                - apk --no-cache add curl; cp /tmp/backup-psql.sh /etc/backup-script/; chmod +x /etc/backup-script/backup-psql.sh; /etc/backup-script/backup-psql.sh
              volumeMounts:
                - name: script-vol
                  mountPath: "/tmp/"
                - name: backup-script
                  mountPath: /etc/backup-script
                - name: db-backup
                  mountPath: /etc/db-backup
          restartPolicy: Never
          volumes:
            - name: backup-script
              emptyDir: { }
            - name: db-backup
              emptyDir: { }
            - name: script-vol
              configMap:
                name: ex310-config-map
                items:
                  - key: "backup-psql.sh"
                    path: "backup-psql.sh"
