apiVersion: v1
kind: Service
metadata:
  name: ex310-todo-app-svc
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: ex310-todo-app
  ports:
    - name: todo-app
      port: 2345
      protocol: TCP
      targetPort: 3002
