apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex104-web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ex104
  template:
    metadata:
      labels:
        app: ex104
    spec:
      containers:
        - name: ex104
          image: dilansachi/devopswk8s-ex104:1.0.0
          imagePullPolicy: IfNotPresent
