apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/service-account.yaml
  - manifests/resource-definition.yaml
  - manifests/cluster-role.yaml
  - manifests/cluster-role-binding.yaml
  - manifests/controller-deployment.yaml
  - manifests/dummy-site.yaml
