apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex401
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ex401
  template:
    metadata:
      labels:
        app: ex401
    spec:
      containers:
        - name: ex401-ping-pong-application
          image: PROJECT/PING_PONG_APP_IMAGE
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3003"
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: ex401-config-map
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: ex401-config-map
                  key: DB_PASSWORD
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: ex401-config-map
                  key: DB_URL
        - name: ex401-log-reader
          image: PROJECT/LOG_READER_IMAGE
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3002"
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: ex401-config-map
                  key: MESSAGE
            - name: PING_PONG_APP_URL
              valueFrom:
                configMapKeyRef:
                  name: ex401-config-map
                  key: PING_PONG_APP_URL
          volumeMounts:
            - name: config-vol
              mountPath: "/config-vol"
              readOnly: true
      volumes:
        - name: config-vol
          configMap:
            name: ex401-config-map
            items:
              - key: "information.txt"
                path: "information.txt"
