apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
  namespace: exercises
data:
  MESSAGE: "hello world"
  PING_PONG_URL: "http://ex205-ping-pong-app-svc:2346"
  information.txt: |-
    this text is from file