apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ex205-ingress
  namespace: exercises
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: ex205-svc
                port:
                  number: 2345
          - path: /pingpong
            pathType: Exact
            backend:
              service:
                name: ex205-svc
                port:
                  number: 2346
