apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ex205-vol-claim
  namespace: exercises
spec:
  storageClassName: ex205-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
