apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ex307-postgres-stset
  namespace: project
spec:
  serviceName: ex307-postgres-svc
  replicas: 1
  selector:
    matchLabels:
      app: ex307-postgresapp
  template:
    metadata:
      labels:
        app: ex307-postgresapp
    spec:
      containers:
        - name: postgres
          image: postgres:16.11-alpine3.23
          ports:
            - name: dbport
              containerPort: 5432
          volumeMounts:
            - name: postgres-data-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
            - name: init-vol
              mountPath: "/docker-entrypoint-initdb.d/"
              readOnly: true
          env:
            - name: POSTGRES_PASSWORD
              value: "postgres_pass"
      volumes:
        - name: init-vol
          configMap:
            name: ex307-config-map
            items:
              - key: "init-db.sql"
                path: "init-db.sql"
  volumeClaimTemplates:
    - metadata:
        name: postgres-data-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ex307-postgres-svc
  namespace: project
  labels:
    app: ex307-postgres
spec:
  ports:
    - port: 5432
      name: dbport
      protocol: TCP
      targetPort: 5432
  clusterIP: None
  selector:
    app: ex307-postgresapp
