apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: ex307-route
  namespace: project
spec:
  parentRefs:
    - name: ex307-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: ex307-svc
          port: 2345
    - matches:
        - path:
            type: PathPrefix
            value: /image
      backendRefs:
        - name: ex307-svc
          port: 2345
    - matches:
        - path:
            type: PathPrefix
            value: /gettodos
      backendRefs:
        - name: ex307-svc
          port: 2346
    - matches:
        - path:
            type: PathPrefix
            value: /addtodo
      backendRefs:
        - name: ex307-svc
          port: 2346
