name: Build & Release Exercise

on:
  push:
    paths:
      - 'ex407/**'
    branches:
      - '**'
    tags-ignore:
      - '**'
  workflow_dispatch:

env:
  LOG_READER_IMAGE_NAME: devopswk8s-ex407-log-reader
  LOG_WRITER_IMAGE_NAME: devopswk8s-ex407-log-writer
  PING_PONG_APP_IMAGE_NAME: devopswk8s-ex407-ping-pong-application
  SERVICE: ex407
  BRANCH: ${{ github.ref_name }}
  DIRECTORY: "ex407"

jobs:
  build-publish-deploy:
    name: Build, Publish and Release
    runs-on: ubuntu-latest
    environment:
      name: dwk-env
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: 'Set namespace'
        run: |
          if [[ "$BRANCH" = "main" ]]
          then
            echo "NAMESPACE=exercises" >> $GITHUB_ENV
          else
            echo "NAMESPACE=$BRANCH" >> $GITHUB_ENV
          fi
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: 'Form the log reader image name'
        run: echo "LOG_READER_IMAGE_TAG=${{ secrets.DOCKER_HUB_USERNAME }}/$LOG_READER_IMAGE_NAME:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV
      - name: 'Form the ping pong app image name'
        run: echo "PING_PONG_APP_IMAGE_TAG=${{ secrets.DOCKER_HUB_USERNAME }}/$PING_PONG_APP_IMAGE_NAME:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV
      - name: 'Form the log writer app image name'
        run: echo "LOG_WRITER_IMAGE_TAG=${{ secrets.DOCKER_HUB_USERNAME }}/$LOG_WRITER_IMAGE_NAME:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV
      - name: 'Setup java23'
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '23'
      - name: Build images
        run: |
          cd $DIRECTORY
          bash build.sh "1" $LOG_READER_IMAGE_TAG $PING_PONG_APP_IMAGE_TAG $LOG_WRITER_IMAGE_TAG
      - name: Publish images
        run: |
          docker push $LOG_READER_IMAGE_TAG
          docker push $LOG_WRITER_IMAGE_TAG
          docker push $PING_PONG_APP_IMAGE_TAG
      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0
      - name: Set image names
        run: |
          cd $DIRECTORY
          kustomize edit set namespace $NAMESPACE
          kustomize edit set image PROJECT/LOG_READER_IMAGE=$LOG_READER_IMAGE_TAG
          kustomize edit set image PROJECT/LOG_WRITER_IMAGE=$LOG_WRITER_IMAGE_TAG
          kustomize edit set image PROJECT/PING_PONG_APP_IMAGE=$PING_PONG_APP_IMAGE_TAG
      - name: Commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: '${{env.DIRECTORY}}/kustomization.yaml'
          message: New version released ${{ github.sha }}
