apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex106-web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ex106
  template:
    metadata:
      labels:
        app: ex106
    spec:
      containers:
        - name: ex106
          image: dilansachi/devopswk8s-ex106:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3001"
