apiVersion: v1
kind: Service
metadata:
  name: ex106-web-server-svc
spec:
  type: NodePort
  selector:
    app: ex106
  ports:
    - name: http
      nodePort: 30080
      protocol: TCP
      port: 1234
      targetPort: 3001
