apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ex111-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: ex111-log-app-svc
                port:
                  number: 2345
          - path: /pingpong
            pathType: Exact
            backend:
              service:
                name: ex111-ping-pong-app-svc
                port:
                  number: 2346
