apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex111-log-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ex111-log-app
  template:
    metadata:
      labels:
        app: ex111-log-app
    spec:
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: ex111-vol-claim
      containers:
        - name: ex111-log-reader
          image: dilansachi/devopswk8s-ex111-log-reader:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3002"
          volumeMounts:
            - name: shared-volume
              mountPath: /usr/src/app/files
        - name: ex111-log-writer
          image: dilansachi/devopswk8s-ex111-log-writer:1.0.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: shared-volume
              mountPath: /usr/src/app/files
