apiVersion: v1
kind: Service
metadata:
  name: ex111-log-app-svc
spec:
  type: ClusterIP
  selector:
    app: ex111-log-app
  ports:
    - name: log-app
      port: 2345
      protocol: TCP
      targetPort: 3002
