apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex111-ping-pong-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ex111-ping-pong-app
  template:
    metadata:
      labels:
        app: ex111-ping-pong-app
    spec:
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: ex111-vol-claim
      containers:
        - name: ex111-ping-pong-application
          image: dilansachi/devopswk8s-ex111-ping-pong-application:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3003"
          volumeMounts:
            - name: shared-volume
              mountPath: /usr/src/app/files
