apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex301-ping-pong-app
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ex301-ping-pong-app
  template:
    metadata:
      labels:
        app: ex301-ping-pong-app
    spec:
      containers:
        - name: ex301-ping-pong-application
          image: dilansachi/devopswk8s-ex301-ping-pong-application:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3003"
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: ex301-config-map
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: ex301-config-map
                  key: DB_PASSWORD
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: ex301-config-map
                  key: DB_URL
