apiVersion: v1
kind: Service
metadata:
  name: ex301-ping-pong-app-svc
  namespace: exercises
spec:
  type: LoadBalancer
  selector:
    app: ex301-ping-pong-app
  ports:
    - name: ping-pong-app
      port: 2346
      protocol: TCP
      targetPort: 3003
